### ISSUE TITLE
***** WARNING: File bed2.sort has inconsistent naming convention for record

### ISSUE THREAD

**Issue by ZhikunWu** [benoukraflab/NanoVar---archived#2]
Why chromosome name starting with 'chr' exist in the bed file? 
I just used the reference genome with chromosome name without 'chr'.

### the command
```
$ nanovar -r  Homo_sapiens.GRCh38.dna.primary_assembly.fa -l M625-0_test.fastq -t 20 -o Project/nanoVar 


NanoVar initiated --- Thu Jun 20 08:53:12 CST 2019
<WARNING: Long read sequencing depth is below recommended depth of more than 4x, output may not be comprehensive>
Traceback (most recent call last):  (32%)
  File "/home/wuzhikun/anaconda3/envs/NanoSV/bin/NanoVar/scripts/nv_lcov_outlier.py", line 186, in <module>
    print main()
  File "/home/wuzhikun/anaconda3/envs/NanoSV/bin/NanoVar/scripts/nv_lcov_outlier.py", line 177, in main
    curve(data2, n, round((medad*6) + med, 0))
  File "/home/wuzhikun/anaconda3/envs/NanoSV/bin/NanoVar/scripts/nv_lcov_outlier.py", line 136, in curve
    smooth = spline(c,y,xnew)
  File "/home/wuzhikun/anaconda3/envs/NanoSV/bin/NanoVar/nv_virtualenv/lib/python2.7/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/wuzhikun/anaconda3/envs/NanoSV/bin/NanoVar/nv_virtualenv/lib/python2.7/site-packages/scipy/interpolate/interpolate.py", line 2918, in spline
    return spleval(splmake(xk, yk, order=order, kind=kind, conds=conds), xnew)
  File "/home/wuzhikun/anaconda3/envs/NanoSV/bin/NanoVar/nv_virtualenv/lib/python2.7/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/wuzhikun/anaconda3/envs/NanoSV/bin/NanoVar/nv_virtualenv/lib/python2.7/site-packages/scipy/interpolate/interpolate.py", line 2827, in splmake
    coefs = func(xk, yk, order, conds, B)
  File "/home/wuzhikun/anaconda3/envs/NanoSV/bin/NanoVar/nv_virtualenv/lib/python2.7/site-packages/scipy/interpolate/interpolate.py", line 2743, in _find_smoothest
    J = _fitpack._bspldismat(order, xk)
ValueError: too few samples (0)
awk: cmd. line:1: {if (>$11+$13 && $11+$13>=1) print $0}
awk: cmd. line:1:      ^ syntax error
awk: cmd. line:1: {if (>$11+$13 && $11+$13>=1) print $0}
awk: cmd. line:1:                            ^ syntax error
***** WARNING: File bed2.sort has inconsistent naming convention for record:
chr1	8695050	8695150	8eba26d1-af9a-41f8-b59d-7c178244812e~D9JRT-l	Inter

***** WARNING: File bed2.sort has inconsistent naming convention for record:
chr1	8695050	8695150	8eba26d1-af9a-41f8-b59d-7c178244812e~D9JRT-l	Inter

***** WARNING: File bed4.sort has inconsistent naming convention for record:
chr1	8695100	8695101	8eba26d1-af9a-41f8-b59d-7c178244812e~D9JRT

***** WARNING: File bed4.sort has inconsistent naming convention for record:
chr1	8695100	8695101	8eba26d1-af9a-41f8-b59d-7c178244812e~D9JRT

Traceback (most recent call last):
  File "/home/wuzhikun/anaconda3/envs/NanoSV/bin/NanoVar/scripts/nv_lr_overlap.py", line 468, in <module>
    main()
  File "/home/wuzhikun/anaconda3/envs/NanoSV/bin/NanoVar/scripts/nv_lr_overlap.py", line 465, in main
    print ''.join(output)
IOError: [Errno 32] Broken pipe
***SV Overlap file required***
```

### some outputs of bed file
```
1       114008484       114008485       004b9ad2-7d29-4551-810d-3eea8f4d6fba~W7G81-l    Inv
1       114017276       114017277       004b9ad2-7d29-4551-810d-3eea8f4d6fba~W7G81-r    Inv
2       207066285       207066286       005415d7-eb64-4066-81a8-8f56dbde7072~Z74K9-l    Del
2       207066420       207066421       005415d7-eb64-4066-81a8-8f56dbde7072~Z74K9-r    Del
chr19   8737550 8737551 00615688-1316-49f4-a5ba-0509160fb232~QHKRD-l    Inter
chr8    1180748 1180749 00615688-1316-49f4-a5ba-0509160fb232~QHKRD-r    Inter
8       1186230 1186231 00615688-1316-49f4-a5ba-0509160fb232~Q03T9-l    Del
8       1186420 1186421 00615688-1316-49f4-a5ba-0509160fb232~Q03T9-r    Del
8       1203368 1203369 00615688-1316-49f4-a5ba-0509160fb232~7UH6N-l    bp_Nov_Ins
18      21323540        21323541        007f8067-7c62-4740-ac25-ce22408e023d~FS3E5-l    Del
18      21323859        21323860        007f8067-7c62-4740-ac25-ce22408e023d~FS3E5-r    Del
chr20   29401544        29401545        00a122de-0fc7-4d59-8a28-2ecb740e1e38~YSCE3-l    Inter
chr3    75678747        75678748        00a122de-0fc7-4d59-8a28-2ecb740e1e38~YSCE3-r    Inter
9       10966651        10966652        00bc5252-7494-4d94-8d17-31636a5cd979~Y8ZAN-l    bp_Nov_Ins
chr13   54314747        54314748        00bc5252-7494-4d94-8d17-31636a5cd979~J05OC-l    Inter
chr9    10965652        10965653        00bc5252-7494-4d94-8d17-31636a5cd979~J05OC-r    Inter

```

### Long read sequencing depth is below recommended depth of more than 4x, output may not be comprehensive

I used nanovar wrapped with docker to run, and had the error **WARNING: Long read sequencing depth is below recommended depth of more than 4x, output may not be comprehensive**,but the input fastq file is at least 15 X.

This is the log file:
```
Log file for NanoVar-1.0.
Thu Jun 20 12:17:42 UTC 2019
Command /usr/local/bin/nanovar -r /root/database/genome/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa -l /root/Project/NanoTrio/clean/M625-0.fastq.gz -t 20 -o /root/Test/nanovar
<Long read fasta file contains no spaces> --- PASSED
<Long read fasta file contains no wraped lines> --- PASSED
nanovar_run directory already present
nanovar_results directory already present
figures directory already present
bowtie2_shortreads directory already present
hsblast_longreads directory already present

Inputs and parameters:
main=/home/NanoVar
refgenome=/root/database/genome/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa
longread=/root/Project/NanoTrio/clean/M625-0.fastq.gz
shortread1=NIL
shortread2=NIL
Short paired-end reads not provided, only long reads will be used for SV characterization
output_dir=/root/Test/nanovar
no_of_threads=20
Genomic_region_excluded_file=0
Neural_network_threshold=0
SV_threshold_score=2.6
SV_alignment_threshold=0.95
Buffered_SV_length_threshold=50
minimum_short_cov=NA
maximum_short_cov=NA
Total_long_reads=2468218

Starting run...
SKIPPING - Build BLAST DB
[Thu-20-Jun 12:17:42] Generate freq counts file
SKIPPING - Convert frequency counts file to obinary
SKIPPING - Build FMD index
SKIPPING - HS-BLAST read alignment search
[Thu-20-Jun 12:43:21] HS-BLAST Parse
<WARNING: Long read sequencing depth is below recommended depth of more than 4x, output may not be comprehensive>

Longread_overlap_upper_limit=
Genome_size=3099750718 bases
Mapped_bases=0 bases
Seq_depth=<1 x
Number_of_splits=1
Splitted_coverage=0.0

***HS-BLAST parsed file required!***

```

But the input fastq file is at least 15X, I don't why has this error.
```
-rw-rw-r--  39G Mar 29 02:37 Project/NanoTrio/clean/M625-0.fastq.gz
```

**Comment by benoukraflab** [comment]
Hi ZhikunWu,

Thank you for trying out NanoVar.

The chromosome naming error is a bug. I have fixed it in the latest version 1.0.1. Please clone the latest version and try again. Thank you for raising the issue.

As for the depth of coverage, I noticed from your log file that certain steps were skipped (e.g. HS-BLAST read alignment search) which might be due to remaining files from a previous run. Hence, the read alignment is not carried out correctly as seen in "Mapped_bases=0 bases". I would suggest to rerun it in a completely empty new directory. 

Thanks!
cytham

**Comment by ZhikunWu** [comment]
Hi cytham,

Thank you! I will try the new version and rerun with your suggestion.

**Comment by benoukraflab** [comment]
You are welcome. 

Anyway, I recommend using the GAP region filter parameter and argument “-f hg38” to prevent false positive SVs arising from the telomeric/centromeric regions. Please refer to the README or wiki for more information.
